version: '3.1'

services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=eventool
    ports:
      - "5432:5432"